exec: remove trailing slash from to-be-cloned URL
Under some circumstances, it seems that a trailing slash can cause the
`git clone` to fail:

    $ bin/configlet sync -e clock
    Cloning https://github.com/exercism/problem-specifications/... failure
    Cloning into '/Users/mark/Library/Caches/exercism/configlet/problem-specifications'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

The same user saw `git clone` fail with the trailing slash:

    $ code git clone https://github.com/exercism/problem-specifications/
    Cloning into 'problem-specifications'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

but succeed without it:

    $ code git clone https://github.com/exercism/problem-specifications
    Cloning into 'problem-specifications'...
    remote: Enumerating objects: 12177, done.
    remote: Counting objects: 100% (1125/1125), done.
    remote: Compressing objects: 100% (354/354), done.
    remote: Total 12177 (delta 911), reused 843 (delta 769), pack-reused 11052
    Receiving objects: 100% (12177/12177), 2.69 MiB | 3.23 MiB/s, done.
    Resolving deltas: 100% (7363/7363), done.

The trailing slash shouldn't be there anyway. Let's remove it.

Fixes: 599