helpers, lint(track_config), sync_common: improve jsony parsing error
Consider the case of a JSON file with a type mismatch, such as the below
contents of a `.meta/config.json` file

    {
      "blurb": 7
    }

If the user runs

    configlet -t /path/to/track/repo sync

before this commit, they would see

    Checking exercises...
    jsony.nim(46)            parseHook
    Error: unhandled exception: Expected " but got 7 instead. At offset: 13 [JsonError]

With this commit, they now see something like

    Checking exercises...
    JSON parsing error:
    /path/to/track/repo/exercises/practice/darts/.meta/config.json(2, 12): Expected " but got 7 instead.

In particular, they see the path of the file with the problem, and the
line number rather than just the offset.

See also commit 6b215a331134