Fix(cli): Show error message for missing value
For example, the command:
  `canonical_data_syncer --verbosity`

Now produces:
  Error: '--verbosity' was given without a value

And shows the help message.

Previously, the program silently ignored the missing value.

Fixes: #37