sync(probspecs): fix message for missing prob-specs dir (#471)
When performing an offline sync, and specifying a problem-specifications
directory that does not exist, for example via

    $ configlet sync --offline --prob-specs-dir /foo/bar

before this commit, we would see this misleading message:

    Checking exercises...
    Every Practice Exercise has up-to-date docs, filepaths, metadata, and tests!

With this commit, we see:

    Checking exercises...
    Error: the given problem-specifications directory does not exist: '/foo/bar'

We also now perform extra validation of the given problem-specifications
directory when `--offline` was passed, checking that:

- It is a git repo

- The working directory is clean

- A remote points to github.com/exercism/problem-specifications

We can improve these checks later, but we already performed these
(and more) when `--offline` was not passed.

This commit also adds a comment, and fixes a parameter name in a doc
comment.

Fixes: #74