lint(track_config): workaround upstream breaking change in jsony
This commit fixes an ambiguous call error that is due to a recent jsony
commit [1] and release [2], and the fact that we're using the latest
version of every dependency because nimble doesn't have lockfiles yet.

A recent CI build [3] failed with the below

    /home/runner/work/configlet/configlet/src/lint/track_config.nim(336, 29) Error: ambiguous identifier: 'SomeSet' -- use one of the following:
      sets.SomeSet: SomeSet
      jsony.SomeSet: SomeSet
         Error: Build failed for package: configlet
            ... Execution failed with exit code 1
         Error: Exception raised during nimble script execution
            ... Command: /home/runner/.nimble/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=4.0.0 --path:/home/runner/.nimble/pkgs/parsetoml-0.6.0 --path:/home/runner/.nimble/pkgs/cligen-1.5.19 --path:/home/runner/.nimble/pkgs/uuids-0.1.11 --path:/home/runner/.nimble/pkgs/isaac-0.1.3 --path:/home/runner/.nimble/pkgs/jsony-1.1.0 -o:/home/runner/work/configlet/configlet/configlet /home/runner/work/configlet/configlet/src/configlet.nim

    /home/runner/work/configlet/configlet/tests/test_binary.nim(1015) test_binary
    /home/runner/work/configlet/configlet/tests/test_binary.nim(879) main
    /home/runner/work/configlet/configlet/src/exec.nim(68) execAndCheck
    Error: unhandled exception:  [OSError]
    Error: execution of an external program failed: '/home/runner/.cache/nim/all_tests_d/all_tests_C96C35B5B5416E192EA4F7BB0F7AD37B1F21B21B '
    stack trace: (most recent call last)
    /tmp/nimblecache-946033505/nimscriptapi_3388874764.nim(187, 16)
    /home/runner/work/configlet/configlet/configlet.nimble(17, 8) testTask
    /home/runner/.choosenim/toolchains/nim-1.6.0/lib/system/nimscript.nim(273, 7) exec
    /home/runner/.choosenim/toolchains/nim-1.6.0/lib/system/nimscript.nim(273, 7) Error: unhandled exception: FAILED: nim r ./tests/all_tests.nim [OSError]
    Error: Process completed with exit code 1.

[1] https://github.com/treeform/jsony/commit/ebee42e04b13
[2] https://github.com/treeform/jsony/releases (1.1.0, on 2021-11-04)
[3] https://github.com/exercism/configlet/runs/4118609366