config: macos: try to fix error for missing SecRandom.h
`Security/SecRandom.h` was still not found when cross-compiling for
arm64 macos, even when building on macos:

    /Users/runner/.cache/nim/configlet_r/@m..@snimdir@slib@sstd@ssysrand.nim.c:9:10: fatal error: 'Security/SecRandom.h' file not found
             ^~~~~~~~~~~~~~~~~~~~~~
    nimble.nim(229)          buildFromDir
    1 error generated.

    Error: execution of an external compiler program 'zigcc -c -w -ferror-limit=3 -pthread -target aarch64-macos-none -Os   -I/Users/runner/work/configlet/configlet/nimdir/lib -I/Users/runner/work/configlet/configlet/src -o /Users/runner/.cache/nim/configlet_r/@m..@snimdir@slib@sstd@ssysrand.nim.c.o /Users/runner/.cache/nim/configlet_r/@m..@snimdir@slib@sstd@ssysrand.nim.c' failed with exit code: 1
    Error:  Build failed for the package: configlet