sync, info: improve "failed to update prob-specs cache" error
Before this commit, running a `configlet sync` or `configlet info`
command when all these conditions were satisfied:

- The problem-specifications cache was present and valid
- but we failed to update the cache due to a network error
- and the --offline option was not passed

produced an unhelpful error:

    $ configlet sync
    Updating cached 'problem-specifications' data...
    fatal: unable to access 'https://github.com/exercism/problem-specifications/': Could not resolve host: github.com

    failed to fetch 'main' in problem-specifications directory: '/home/foo/.cache/exercism/configlet/problem-specifications'
    exec.nim(68)             execAndCheck
    Error: unhandled exception:  [OSError]

With this commit, configlet explains what the user can do next:

    $ configlet sync
    Updating cached 'problem-specifications' data...
    fatal: unable to access 'https://github.com/exercism/problem-specifications/': Could not resolve host: github.com

    failed to fetch 'main' in problem-specifications directory: '/home/foo/.cache/exercism/configlet/problem-specifications'
    Error: Unable to update the problem-specifications cache.

    You can either:

    - ensure that you have network connectivity, and run the same configlet command again
    - or add the '--offline' option to skip updating the cache

    The most recent commit in the problem-specifications cache is:

        commit 7012a73188698b2b7a2c340c1753d0198a38d8fa
        Author:     Katrina Owen <katrina.owen@gmail.com>
        CommitDate: Mon, 17 Oct 2022 16:36:08 +0200

            Change wording in tournament instructions (#2135)

Fixes: 683