Revert ".github(cross-compile): try enabling -flto on macOS"
This reverts commit d0e67f65236de7abbe1aa6a5c76b64c0cbdd8909.

It produced the error:

    error: LTO is not yet supported with the Mach-O object format. More details: https://github.com/ziglang/zig/issues/8680