exec: remove trailing slash from to-be-cloned URL (#600)
Under some rare circumstance, it seems that `configlet sync` could fail
during the `git clone` part:

    $ configlet sync -e clock
    Cloning https://github.com/exercism/problem-specifications/... failure
    Cloning into '/Users/foo/Library/Caches/exercism/configlet/problem-specifications'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

And this seems to be due to a trailing slash. The same user saw
`git clone` fail when using a trailing slash:

    $ git clone https://github.com/exercism/problem-specifications/
    Cloning into 'problem-specifications'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

but succeed without it:

    $ git clone https://github.com/exercism/problem-specifications
    Cloning into 'problem-specifications'...
    remote: Enumerating objects: 12177, done.
    remote: Counting objects: 100% (1125/1125), done.
    remote: Compressing objects: 100% (354/354), done.
    remote: Total 12177 (delta 911), reused 843 (delta 769), pack-reused 11052
    Receiving objects: 100% (12177/12177), 2.69 MiB | 3.23 MiB/s, done.
    Resolving deltas: 100% (7363/7363), done.

I can't reproduce the issue on any platform, and the cause may be some
particular git configuration, but let's remove the trailing slash.

Fixes: #599