sync(probspecs): fix message for missing prob-specs dir
When performing an offline sync, and specifying a problem-specifications
directory that does not exist, e.g. via

    $ configlet sync -o -p /foo/bar

before this commit, we would see this misleading message:

    Checking exercises...
    Every Practice Exercise has up-to-date docs, filepaths, metadata, and tests!

But with this commit, we see:

    Checking exercises...
    Error: the given problem-specifications directory does not exist: '/foo/bar'

Fixes: 74