nimble: set version from `configlet.version` file (#616)
Configlet has been using pre-release semantic versions (which contain a
hyphen) like `4.0.0-beta.1`. However, such a version is currently
not allowed in the nimble file:

    $ nimble check
         Error: Version may only consist of numbers and the '.' character but found '-'.
       Failure: Validation failed

As a workaround, we have been specifying the configlet version in a
custom `configlet.version` file (see commit e90c5ec19be6) that can
contain anything.

Let's use that file to set the nimble file `version`. This will allow
future major/minor/patch version bumps to occur only in the dedicated
file, like the pre-release ones, which will also simplify the version
bumping script.

This commit does not change the version string:

    $ nimble dump | grep version
    version: "4.0.0"