Fix(cli): Hide error for argument of `help`
The previous commit means that if the user wrote:
  `canonical_data_syncer help`

The program printed:
  Error: invalid argument: 'help'

and then showed the help message. This commit hides that error, so that
only the help message is shown for this special case.

See: #35